Update for eForms
open-contracting-extensions/ocds_techniques_extension pull request #8
Opened 2023-05-30 03:14 UTC by duncandewhurst

2023-06-01 16:15 UTC, odscjen requested changes

2023-06-01 16:15 UTC, odscjen commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BG-706 (Techniques)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). For correspondences to eForms fields, se
```suggestion
In the European Union, this extension's fields correspond to [eForms BG-706 (Techniques), BG-557 (Group Framework Maximum Value and BT-271 (Framework Maximum Value)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). For correspondences to eForms fields, see [OCDS for eForms](https://standard.open-contracting.org/profiles/eforms/latest/). For correspondences to Tenders Electronic Daily (TED), see [OCDS for the European Union](http://standard.open-contracting.org/profiles/eu/master/en/).
```

2023-06-01 16:15 UTC, odscjen commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
Should the description of `value` also have a secondary sentence part describing that it should be used at the award and contract stages?

2023-06-07 22:59 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
Hmm, techniques only appear in the `tender` section, does it make sense to put actual award/contract values there?

2023-06-08 01:51 UTC, jpmckinney commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
OCDS 1.2 has `Award.maximumValue` for framework agreements (also, `Award.estimatedValue`).

2023-06-09 15:29 UTC, odscjen commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
tbh I'm now not sure what I was getting at with this comment! I think the point was that "The total upper estimated value of the framework agreement" and "The estimated maximum value of the framework agreement," are identical in meaning, it's only the second part of the description of `maximumValue` that differentiates it from `value`. So the definition of `value` needs something to make it clearer why both of these fields exist and which to use in any specific circumstance?

2023-06-09 15:31 UTC, jpmckinney commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
Ah, actually do we need to add `maximumValue` then? Is it used for another mapping?

2023-06-09 15:48 UTC, odscjen commented on README.md
> +In the European Union, this extension's fields correspond to [eForms BG-706 (Techniques), BG-557 (Group Framework Maximum Value and BT-271 (Framework Maximum Value)](https://docs.ted.europa.eu/eforms
```suggestion
In the European Union, this extension's fields correspond to [eForms BG-706 (Techniques), BG-157 (Group Framework Maximum Value and BT-271 (Framework Maximum Value)](https://docs.ted.europa.eu/eforms/latest/reference/business-terms/). For correspondences to eForms fields, see [OCDS for eForms](https://standard.open-contracting.org/profiles/eforms/latest/). For correspondences to Tenders Electronic Daily (TED), see [OCDS for the European Union](http://standard.open-contracting.org/profiles/eu/master/en/).
```
Sorry I think I introduced a typo

2023-06-09 16:01 UTC, odscjen commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
So there are 2 fields relevant here -  
* BT-271 (Framework Maximum Value) which we've mapped to `techniques.frameworkAgreement.maximumValue` 
* BT-157 (Group Framework Maximum Value) which we've mapped to `techniques.frameworkAgreement.value`.

BT-157 is only in `guidance.yaml` for LotsGroup, but BT-271 has both a Lot and a LotsGroup version.  

Looking at the definitions:

BT-157 = "The maximum value which may be spent in a framework agreement within a group of lots. This information can be provided when the maximum value of a group of lots is lower than the sum of maximum values of individual lots in this group (e.g. when the same budget is shared for several lots).  Maximum value means a value covering all contracts to be awarded within a framework agreement over its whole duration, including options and renewals."

BT-271 = "The maximum value of the framework agreement for the procurement procedure or lot, over its whole duration, including options and renewals. This value covers all contracts to be awarded within the framework agreement." The [guidance](https://docs.ted.europa.eu/eforms/latest/schema/all-in-one.html#estimatedValueSection) also states that this field "represents the early evaluation of the Framework Maximum value for the Group of Lots, the Lot or the Procedure as a whole."

The difference (in my reading) is that BT-271 is the aggregated value of all the lots in the group, where BT-157 may be less than the aggregated value if they are sharing a budget? So it is possible that over the course of related notices both of these values could be used which is why we added in the `maximumValue` field? In which case we do need both but I think the definition of at least one needs updating.

2023-06-09 16:32 UTC, jpmckinney commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
I think BT-271 matches the existing `value` field. It's the maximum value of the FA for the procedure (tender) or lot.

BT-157 is only for lot groups. So that would map to LotGroup.maximumValue (not sure if it's already in use).

2023-06-12 08:48 UTC, odscjen commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
It is, BT-27-LotsGroup (Estimated Value) is currently mapped to `lotGroups.maximumValue`

2023-06-12 15:18 UTC, jpmckinney commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
Do you have an idea what the difference is, in semantics, between BT-27-LotsGroup and BT-157-LotsGroup?

At any rate, BT-157-LotsGroup seems more like `maximumValue` and `BT-27-LotsGroup` more like `value`.

2023-06-12 15:20 UTC, jpmckinney commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
Ah, BT-157 is specific to framework agreements, but BT-27 is not.

2023-06-12 15:41 UTC, jpmckinney commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
This analysis got a bit long so I reopened https://github.com/open-contracting/european-union-support/issues/121

2023-06-13 22:12 UTC, duncandewhurst commented on release-schema.json
> +          "description": "The estimated maximum value of the framework agreement, as estimated when publishing the tender information.",
I've removed `FrameworkAgreement.maximumValue` per https://github.com/open-contracting/european-union-support/issues/121#issuecomment-1588935142

2023-06-19 14:26 UTC, odscjen approved these changes

2023-06-20 21:58 UTC, jpmckinney approved these changes

2023-06-20 21:58 UTC, merged